 # -*- mode: org; -*-
 # Time-stamp: <2020-05-14 10:45:01 lockywolf>
 # Created   : [2020-05-11 Mon 21:01]
 # Author    : lockywolf gmail.com
 #+STARTUP: inlineimages
 #+STARTUP: latexpreview
 #+HTML_MATHJAX: align: left indent: 5em tagside: left font: Neo-Euler
 #+HTML_MATHJAX: cancel.js noErrors.js
 #+OPTIONS: tex:imagemagick

https://github.com/jkitchin/org-ref
https://jonathanabennett.github.io/blog/2019/05/29/writing-academic-papers-with-org-mode/
http://web.archive.org/web/20190501044840/http://www.mfasold.net/blog/2009/02/using-emacs-org-mode-to-draft-papers
https://orgmode.org/worg/org-faq.html#using-reftex-in-org-mode

This report is written as a post-mortem of a project which has,
perhaps been the largest personal project of the author: creating a
complete and wholesome solution to one of the most famous programming
problem sets in the modern computer science curricula "Structure and
Interpretation of Computer Programs" by Abelson, Sussman and Sussman.

It measures exactly:
- How much effort SICP requires (739 hours 19 minutes, 8 months, 292 sessions)
- How many computer languages it involves (6)
- How many pieces of software are required ()
- How much communication with peers is needed

It suggests:
- An applied task management software-backed procedure
- Improvements on the technical side of any hard skills teaching
- Improvements on the social side of any kind of teaching

* Introduction

Programming language textbooks are not a frequent object of study, as
they are expected to convey existing knowledge. However, teaching
practitioners, when they face the task of designing computer science
curriculum for their teaching institution, have to base their decision
on something. An "ad-hoc" teaching method, largely based on studying
some particular programming language fashionable at the time of
selection, is still a popular choice. 

However, there have been attempts to approach the design of a course
with more rigour, and the very famous "Structure and Interpretation of
Computer Programs" was born as a result of this attempt. SICP was
revolutionary for its time, and perhaps can be still considered
revolutionary nowadays. Twenty years later this endeavour was analysed
by Felleisen in a paper "Structure And Interpretation of Computer
Science Curriculum" TODO, in which he reflected upon the benefits and
drawbacks of the ~deliberately designed~ syllabus from the pedagogical
standpoint, and proposes what he believes to be a pedagogically
superior successor to the first generation of a ~deliberate~
curriculum. (How to Design Programs TODO, HTDP)

Leaving aside the pedagogical quality of the textbook (as the author
is not a practising teacher), this report touches a different (and
seldom considered!) aspect of a computer science (and in general, any
other subject's) curriculum. That is, it's how much work exactly is
required to pass a particular course.

This endeavour was spurned by the author's previous experience of
learning Partial Differential Equations using a traditional
paper-and-pen based approach, only mildly augmented with a
time-tracking software. But even such a tiny augmentation already
exposed an astonishing disparity between a declared labouriousness of
a task and the real time required to complete it. TODO (reference to
my own facebook)

The author therefore decided to build upon the previous experience and
to try and design an as smooth, manageable (the definition of
manageable reference TODO), and measurable approach to performing
university coursework, as possible. A computer science subject
therefore provided an obvious choice.

The solution was decided, broken down into parts, harnesses with a
software support system, and executed in a timely and measured manner
by the author, thus proving that the chosen goal is doable. The
complete measured data are provided. Teaching professionals may
benefit from it when planning their own coursework.

More generally, the author wants to propose a comprehensive
reassessment of university teaching in general, on the basis of
empiric approach (understanding exactly what and when every party
involved in the teaching process does), in order to select the most
efficient (potentially even using a gradient-based optimisation
algorithm) strategy when selecting a learning approach for every
particular student.


* Solution approach

 I, the author, wanted to provide a solution that would satisfy the
following principles:

 1. Be complete.
 2. Be a fairly realistic modelling of a solution process as if
executed by the intended audience of the course -- that is freshman
university students with little programming experience. 
 3. Be done in a "fully digital", "digital native" form.
 4. Be measurable.

This principles need an explanation. 

** Completeness
*** Just solve all of the exercises

I consider completeness to be the most important property of every
execution of a teaching syllabus.

In simple words, what does it mean "to pass a course" or "to learn a
subject" at all? How exactly can one formalise the statement "I know
calculus"? Or even a simpler "I have learned everything that was
implied by a university course on calculus". The following are the
potential answers to this questions as they may be given (TODO it would be
better to conduct a survey of teachers, students, employers,
politicians and random members of the community to establish what it
means _for them_):

- Passing an oral examination
- Passing a written examination
- Passing a project defence committee questioning
- Completing a required number of continuous assessment (time-limited) tasks
- Completing coursework
- Attending a prescribed number of teaching sessions (lectures and/or tutorials)
- Reading a prescribed amount of prescribed reading material
- (anything else?)

Any combination of those can be also chosen to signify the "mastering"
of a subject, but the course designer is then met with a typical
goal-attainment multi-objective optimisation problem, which are usually
still solved by reducing the multiple goals to a single engineered goal.

Now if we try to look at this with a "martian standpoint" (TODO Eric
Bern), we will see that all the goals listed above are reducible to
the "completing coursework" goal, whereas "completing coursework" is
not in the most general case reducible to any of those, so the
"engineered goal" may look essentially like a tree-structured
coursework, with possibly several tasks requiring viewing certain
video recordings and writing a response.

Moreover, thinking realistically, doing coursework is the only way
that a working professional can study without completely abandoning
her job.

Therefore, choosing a computer science textbook that is known for the
problem set that comes with it more than for the actual text of the
material was a natural choice.

But that is not enough, because "just solving all of the exercises" may be the most measurable and the most necessary learning outcome, but is it sufficient?

As I wanted to "grasp the skill" rather than just "pass the exercises", I initially decided to consider additional exercises that may be valuable as a process of "engineering a custom problem set".

One of the approaches used to "engineer exercises" is to try an put yourself in the position of a teacher, and ask yourself: "After I finish this book/problem set, will I be able to write my own book on this?".
Even if the answer is "no", continue asking yourself "Okay then. But can I at least create a book that would be conveying exactly the same now myself?".
If the answer is "yes", then learning is successful with high likelihood.

From the practical point, in the "reference solution" attached to this report, you can find exercises that are not a part of the original problem set.
Those were added by me for the very reason "to be able to reproduce the source code of the book from scratch".

*** Meta-cognitive exercises

It is often underestimated how much imbalance there is between a teacher and a pupil, in the sense that the teacher not only knows better the subject of study, that is expected, but is also effectively deciding _now_ and _when_ a student is going to study.
This is often overlooked by practitioners, how consider themselves as either just sources of knowledge, or, even worse, only the examiners.
However, it is worth considering _the whole_ effect that a teacher is having on the student's life.
In particular, a student has no other choice than to trust the teacher on the choice of exercises. 

The main point of the previous paragraph is that the teaching process is not only the process of data transmission.
It is also the process of metadata transmission, the development of meta-cognitive skills.
(TODO reference Falikman)
And therefore, meta-cognitive challenges, although they may very well be valuable contributions to the student's "thinking abilities", deserve their own share of consideration when preparing a course.

The examples of meta-cognitive exercises include:

- Non-sequentiality of material and/or exercises, when earlier ones are impossible to solve without solving later ones.
- Incompleteness of the treatise.
- Terseness of the narrative.
- Lacking of modern software support.
- Missing difficulty/hardness estimation for tasks.
- Vastly non-uniform difficulty of problems.

An additional challenge to the learning process is the lack of peer support.
There has been attempts by learning institutions to encourage peer support among the students, but the successfullness of those attempts is unclear.
Do students really help each other in those artificially created support groups?
How does side-communication, generally irrelevant to the subject of study affect the learners?

A support medium is even more important for adult self-learners, who don't get even those artificial support groups created by the school functionaries.

It should be noted that the support medium choice, no matter how irrelevant to the subject itself it may be, is a very important social factor.
This is not to say that a teacher should create a support group in that particular social medium that is fashionable at the start of the course.
This is only to say that ~deliberate effort~ should be spent on finding the best support configuration.

From the *personal experience*:

- I used the [[irc:irc.freenode.org/#scheme][#scheme freenode channel]] as a place to ask questions in real-time. #emacs was also useful.
- I used stackoverflow.com to ask offline questions.
- I used the scheme community wiki community.schemewiki.org as a reference material.
- I emailed some prominent member of the scheme community with unsolicited questions.
- I was reporting errors in the documents generated by the scheme community process.
- I was asking for help on the Chibi-scheme mailing list.
- There was also some help from the opendatascience Slack chat.
- There was also some help from the Closed-Circles data science community.
- There was also some help from the rulinux@conference.jabber.ru community.
- There was also some help from the Shanghai Linux User Group.
- There was also some help from the www.dxdy.ru scientific forum.
- There was also some help from the Haskell self-study group in Telegram.

It should be noted that out of those communities, only the OpenDataScience community, and a small Haskell community resides in a "fashionable" communication system.

The summary of the community interaction is under the "meta-cognitive" exercises section, because the skill of finding people who can help you with your problems is one of the most important soft skills ever, and one of the most hard to teach.
Moreover, naturally, the people who _can_ and _may_ answer questions are in most of the cases not at all obliged to do so, so soliciting an answer from non-deliberately-cooperating people is another cognitive exercise that is worth looking into.

I will repeat the main point of the previous paragraph in another words: human communities consist of rude people. Naturally, in the modern "free" world, no-one can force anyone to bear rudeness, but no-one can just as much force anyone to be polite.
The meta-cognitive skill of extracting valuable knowledge from willing but rude people is a very important skill.

But returning to the choice of the community, it is important to convey to the students, as well as the teachers, the following idea: it is not the fashion, population, easy availability, promotion, and social acceptability of the support media that matters.
Unfortunately, it is not even the technological advanceness, technological modernity or convenience that matters. It is the availability of information, and the availability of people who can help. This is a painful knowledge worth learning.

Support communication statistics is the following:

- Scheme interpreter related email threads: 28
- Editor/IDE related email threads + bug reports: 16
- Presentation/formatting related email threads: 20
- Syllabus related email threads: 3
- Documentation related email threads (mostly obsolete links): 16
- IRC chat messages: 2394 #scheme messages
- Software packages re-uploaded to source forges: 2

Statistics from other means is hard to collect.

** Behaviour modelling, reenactment and the choice of tools

When I started this project, I already had a Ph.D. in Informatics, although not an engineering one.
This gave me a certain advantage over a first-year undergraduate student.
However, to a large extent I resembled a newbie still, as I had never before used a proudly functional programming language, and had never used any programmer's editor other than Notepad++. The only _really_ distinguishing property of me at the start of the project was that I already had learned the skill of typing quickly and without looking at the keyboard.

*note* All of this report is _heavily_ dependent on the fact that I learned how to "touch type", and can do it relatively fast. Without the fast touch-typing (not looking at the keyboard), almost all of it has no sense, ergonomic suggestions make no sense, and the choice of tools may seem counter-intuitive or even arbitrary. 

The goal I had was slightly schizophrenic, in the sense that I intended to model (reenact) a "normal" student, that is the one that doesn't exist, in the sense that I:

- Decided to perform all exercises honestly, no matter how hard they be or how much time they take.
- Solve all exercises myself. Although that didn't restrict me on consulting other people's solution when this didn't involve direct copying.
- Try to use the tools that may have been available at the disposal of the students in 1987, although possibly the most recent versions.
- Try to follow the "Free Software/Open Source/Unix Way" approach as loosely formulated by the well known organisations, as close as possible. 
- Try to prepare a "problem set solution" in a format that may be potentially presentable to a university teacher in charge of accepting or rejecting it.

While the first three principles turned out to be almost self-fulfilling, the last one turned out to be more involved.

My own personal experience with the university-level programming suggested than on average the largest amount of time is spent on debugging input and output procedures.
The second-largest amount is usually dedicated to inventing test cases for the code.
The actual writing of the substantive part of the code only comes the third.

As I knew that SICP had been intended as a deliberately created introductory course, I assumed that a large part of the syllabus would be dedicated to solving the two most laborious problems.
I was wrong.
Rather than solving them, SICP just goes around, enforcing  a very rigid standard on the input data instead.

The final choice of tools turned out to be the following:

- chibi-scheme :: as it is the scheme implementation
- GNU Emacs :: as the only IDE
  - org-mode :: as the main editing mode and the main planning tool
  - f90-mode :: as a low-level coding adaptor
  - geiser :: turned out to be not really ready for production use
  - magit :: as the most fashionable GUI for git
- gfortran :: as the low-level language
- PlantUML :: as the principal diagramming language
- Tikz + luaLaTeX :: as the secondary diagramming language
- graphviz :: as a tertiary diagramming language
- imagemagick :: as the engine behind the "picture language" chapter
- git :: as the main version control tool
- GNU diff, bash, grep :: as the tools for simple text manipulation

The choice of all the software above except "org-mode" is driven by the "imitative approach".
That is, I tried to imagine myself being an "ideal student" and making the decisions as the imaginary student would be doing them.
Informally this can be summarised as "I will learn every tool that is required to get the job done to the extent needed to get the job done, but not a slightest bit more".

*chibi-scheme* is effectively the only scheme system claiming to support the last scheme standard, r7rs-large (Red Edition), so there was really no other choice.
This is especially true when imagining a student unwilling to go deeper into the particular curiosities of various schools of thought creating various partly-compliant scheme systems.

*git* is not often taught in schools.
Maybe because the teachers don't want to busy themselves with something deemed trivial or impossible to get by without, or due to being overloaded with work.
However, practice often demonstrates that students still too often graduate without yet having a concept of file version control, which significantly hinders work efficiency.
I chose git, because it is, arguably, the most widely used version control system.

*imagemagick* turned out to be the easiest way to draw simple straight line based images from scheme.
There is still no standard way to connect scheme applications to applications written in other languages.
Therefore, by the principle of minimal extension, imagemagick was chosen, as it required ~just a single~ non-standard scheme procedure.
Moreover, this procedure (a simple synchronous application call) is likely to be the most standard interoperability primitive invented.
Almost all operating systems support applications executing other applications.

*PlantUML* is a text-based implementation of the international standard of software visualisation diagrams. 
The syntax is very easy, well documented.
The PlantUML-Emacs interface exists and is relatively reliable.
The textual representation conveys the hacker spirit, and supports easy version control.
UML almost totally dominates the software visualisation market, and almost every university programming degree includes it to some extent.
It seemed therefore very natural to (where the problem permitted) solve the "diagramming" problems of the SICP with the industry standard compliant diagrams.

*graphviz* was used in an attempt to use another industry standard for solving those diagramming problems unsupported by the UML.
The ~dot~ package benefits from being fully machine-parseable and context independent even more than UML. However, it turned out to be not as convenient as expected. 

*TikZ* is essentially the only general-purpose text-based drawing package.
So when neither UML nor DOT managed to properly embed the complexity of the models diagrammed, TikZ ended up being the only choice.
Just as natural of an approach could be drawing everything with a graphical tool, such as Inkscape or Adobe Illustrator.
The first problem with the images generated by them is though that those are hard to manage under version control.
The second problem is that (I will get to it later) for the purposes of easy defendability of the resulting work, it was desirable to keep all the product of the course in one digital artefact (read, one file).

*gfortran*, or GNU Fortran was the low language of choice for the last two problems in the problem set.
The reason for choosing not a very popular language were the following:
- I already knew the C language, so compared to an imaginary first year student I would have an undue advantage.
- Fortran is low-level enough for the purposes of the book.
- There is a free/GPL implementation of Fortran.
- Fortran 90 had already existed by the moment SICP 2nd. Ed. was released.

*GNU Unix Utilities* I didn't originally intend to use, but ~diff~ turned out to be extremely effective in illustrating the difference between generated code pieces in the Chapter 5. Additionally, bash printf had to be used as a bug work-around.

*GNU Emacs*: is de-facto the most popular IDE among scheme users, the IDE used by the Free Software Foundation founders, likely the editor used when writing SICP, also likely to be chosen by an aspiring freshman to be the most "hacker-like" editor.
It is, perhaps, the most controversial choice, as the most likely IDE to be used by freshmen university students in general would be Microsoft Visual Studio.
Another popular option would be Dr.Racket.
However, at the end of the day, Emacs turned out to be having the most superior support for a "generic Lisp" development, even though it's support for scheme is not as good as may be desired.
The decisive victory point actually ended up being the org-mode (discussed later).
Informally speaking, fully buying into the Emacs platform ended up being a huge mind-expanding experience.
The learning curve is steep though.
As I mentioned above, the main point of this report is to supply the problem execution telemetry for public use.
Later I will elaborate on how I collected it, however I can already say that I use org-mode's time tracking facility. However, I had learned Emacs in general before I learned org-mode, and thus only the Emacs Lisp part got covered by time management.

But already here I can list some *data*:
Just reading the Emacs Lisp manual required *10* study sessions of total length 32 hours 40 minutes.
Additional learning of Emacs *without* reading the manual required 59 hours 14 minutes.

This data will be also presented in a table later. TODO

*org-mode*
Imagine a case when a student needs to send his work to the teacher for examination.
Every additional file that a student sends along with the code is a source of confusion.
Even proper file naming, though increases readability, is hard to enforce, and demands that the teacher dig into the peculiarities that will become irrelevant the very moment after he signs the work off.
Things get worse when the teacher has to not only examine the student's work, but also test it.
(Which is a common case with computer science exercises.)

SICP also provides and additional challenge (meta-cognitive exercise) in that its problems are highly dependent on one another.
As an example, problems from Chapter 5 require successfully completed exercises of Chapter 1.
A standard practice of modern schools is to copy the code (or other forms of solution).
However, in the later parts of SICP, the solutions end up requiring up to tens of pieces of code written in the chapters before.
Sheer copying would not just blow up the solution files immensely and make searching painful.
It would also make it extremely hard to back-propagate the bugs discovered by later usages into the earlier solutions.

The third reason to carefully consider the solution format is the future employability of the students.
This problem is not uncommon for the Arts majors, who have been garnering "portfolios" of their work since ages ago.
But this feeling is still generally lacking among technical students.
One of the great discussion subjects on a job interview is "what have you done".
And having a portfolio is of an immense help for the interviewee.

But the potential employer is almost guaranteed to not have any software or equipment to run the former student's code.
And in fact even the student himself would probably be lacking the carefully prepared working setup at the interview.
Therefore, the graduation work should be "stored", or "canned" in an portable and time-resistant format as possible.

Unsurprisingly, the most portable and time-resistant format of practical usage is plain white paper.
So ideally the solutions (after being examined by a teacher) should be printable in the form of a report or a book.
Additionally, the comparatively (to the full size of SICP) small amount of work required to turn a solution that is "just enough to pass" into a readable report would be an important emotional incentive for the students to carefully post-process their work.
Naturally, "plain paper" is not a very manageable medium nowadays.
But the closes, and quite manageable approximation is PDF.
So the actual "source code" of a solution should be logically and consistently exportable into PDF.

This leads us to the idea first proposed by Donald Knuth with his WEB system and its web2c implementation.
The implementation of WEB for Emacs is called org-mode, in particular with its org-babel module.
Another commonly used WEB implementation is called Jupyter.

Org-mode has an almost unimaginable number of use cases.
(In particular, this report has been written in org-mode.)
And while the main benefit of using org-mode for the coursework formatting was the interactivity of code execution, and the possibility of export, another benefit that appeared almost for free was minimal-overhead time-tracking.
(Human performance profiling.)
Although it originally appeared as a by-product of choosing a specific tool, at the end of the day it is the telemetry collected with the aid of it, that is the main contribution of this report.

The way org-mode particulars were used is described in the next section, along with the statistical summary.

** TODO Time analysis, performance profiling and graphs

The execution was performed in the following way: 

Firstly, the heading outline corresponding to the book subsection tree was created.
(See Appendix 1 for the outline and completion times.)
Most leaves are two-state TODO-headings.
(Some leaves correspond to sections without problems, and thus are not TODO-styled.)

Intermediate levels are not TODO-headings, but they contain the field representing the total ratio of DONE problems.

The top level ratio, obviously, looks like the ratio of the total number of finished problems versus the total number of problems.

This allows for constant monitoring of the "degree of completeness" and provides an important emotion of "getting close to the result with each complete exercise".
Additional research is needed on how persistent this emotion is in students and how much it depends of the uneven distribution of hardness or time consumption.
There is, however, empirical evidence that even very imprecise self-measured KPIs do positively affect the chance of reaching the goal.
(TODO reference "the people who measure their weight more often are more fit") 
It should be noted though that even if the hypothesis of uneven time consumption affects the positively stimulating emotion, the problems we find in the real world are not evenly hard, and therefore an even distributions of hardness may negatively affect the development of the meta-cognitive still of partitioning a task in smaller ones.

The problems were executed almost sequentially, and the work on the next one was started immediately after the previous one had been finished.
Deliberate effort was spent on avoiding the cases when a study session ends at the same time as the last problem of the session is done.
This was done in order to exploit the well-known tricks: 

- When you have something undone, it is easier to make yourself start the next session.
- Even just reading out the description of a problem makes you start thinking about how to solve it.

Exercise completion time was registered with a standard org-mode completion time mechanism.

Study sessions were registered in a separate org-mode file in the standard org-mode time interval standard BEGIN_TIME -- END_TIME.
(Appendix 2)




** Materials

*** Books 
- Structure and Interpretation of Computer Programs 2nd Ed.
- Structure and Interpretation of Computer Programs 1st Ed. pre-print
- Modern Fortran Explained 2018
- Revised^7 Report on Algorithmic Language Scheme
- Balbin, I., Lecot, K. (Eds.) Logic Programming: A Classified Bibliography
- Chibi-scheme manual (improvised)
- TikZ manual
- PlantUML manual
- Thomas A. Pender-UML Weekend Crash Course

*** Software
- GNU Emacs
- org-mode for Emacs
- chibi-scheme
- MIT/GNU Scheme
- luaLaTeX/TexLive!
- TikZ/PGF
- PlantUML
- Graphviz
- Slackware Linux 14.2-current


** Appendix 1

Full data on the exercise completion times.

#+begin_example
Snippet, First Scheme Expression
[2019-08-19 Mon 09:19]
Figure 1.1 Tree representation, showing the value of each subcombination
[2019-08-20 Tue 14:35]
Exercise 1.1 Interpreter result
[2019-08-20 Tue 14:23]
Exercise 1.2 Prefix form
[2019-08-20 Tue 14:25]
Exercise 1.3 Sum of squares
[2020-02-28 Fri 12:01]
Exercise 1.4 Compound expressions
[2019-08-20 Tue 14:39]
Exercise 1.5 Ben's test
[2019-08-20 Tue 14:50]
Exercise 1.6 If is a special form
[2019-08-21 Wed 14:05]
Exercise 1.7 Good enough?
[2019-08-22 Thu 12:52]
Exercise 1.8 Newton's method
[2019-08-22 Thu 17:36]
Exercise 1.9 Iterative or recursive?
[2019-08-29 Thu 15:14]
Exercise 1.10 Ackermann's function
[2019-08-25 Sun 18:31]
Exercise 1.11 Recursive vs iterative
[2019-08-25 Sun 19:25]
Exercise 1.12 Recursive Pascal's triangle
[2019-08-25 Sun 19:42]
Exercise 1.13 Fibonacci
[2019-08-25 Sun 23:04]
Exercise 1.14 count-change
[2019-08-30 Fri 16:09]
Exercise 1.15 sine
[2019-08-30 Fri 22:34]
Exercise 1.16 Iterative exponentiation
[2019-08-30 Fri 23:20]
Exercise 1.17 Fast multiplication
[2019-08-30 Fri 23:48]
Exercise 1.18 Iterative multiplication
[2019-08-31 Sat 11:43]
Exercise 1.19 Logarithmic Fibonacci
[2019-09-01 Sun 20:42]
Exercise 1.20 GCD applicative vs normal
[2019-09-01 Sun 23:04]
Exercise 1.21 smallest-divisor
[2019-09-01 Sun 23:43]
Exercise 1.22 timed-prime-test
[2019-09-02 Mon 00:44]
Exercise 1.23 (next test-divisor)
[2019-09-02 Mon 09:56]
Exercise 1.24 Fermat method
[2019-09-02 Mon 11:32]
Exercise 1.25 expmod
[2019-09-02 Mon 12:46]
Exercise 1.26 square vs mul
[2019-09-02 Mon 12:50]
Exercise 1.27 Carmichael numbers
[2019-09-02 Mon 20:50]
Exercise 1.28 Miller-Rabin
[2019-09-02 Mon 23:28]
Exercise 1.29 Simpson's integral
[2019-09-03 Tue 10:36]
Exercise 1.30 Iterative sum
[2019-09-03 Tue 11:19]
Exercise 1.31 Product
[2019-09-03 Tue 11:59]
Exercise 1.32 Accumulator
[2019-09-03 Tue 12:23]
Implement ~sum~ in terms of an iterative accumulator
[2019-09-03 Tue 12:23]
Implement ~product~ in terms of a recursive process
[2019-09-03 Tue 12:22]
Exercise 1.33 filtered-accumulate
[2019-09-03 Tue 14:36]
Exercise 1.34 lambda
[2019-09-03 Tue 14:44]
Exercise 1.35 fixed-point
[2019-09-03 Tue 21:05]
Exercise 1.36 fixed-point-with-dampening
[2019-09-03 Tue 21:55]
Exercise 1.37 cont-frac
[2019-09-04 Wed 11:35]
Exercise 1.38 euler constant
[2019-09-04 Wed 11:35]
Exercise 1.39 tan-cf
[2019-09-04 Wed 12:11]
Exercise 1.40 newtons-method
[2019-09-04 Wed 17:06]
Exercise 1.41 double-double
[2019-09-04 Wed 17:21]
Exercise 1.42 compose
[2019-09-04 Wed 17:27]
Exercise 1.43 repeated
[2019-09-04 Wed 17:54]
Exercise 1.44 smoothing
[2019-09-04 Wed 20:17]
Exercise 1.45 nth-root
[2019-09-04 Wed 21:37]
Exercise 1.46 iterative-improve
[2019-09-04 Wed 22:25]
Exercise 2.1 make-rat
[2019-09-06 Fri 13:00]
Exercise 2.2 make-segment
[2019-09-06 Fri 13:34]
Exercise 2.3 make-rectangle
[2019-09-08 Sun 17:58]
Exercise 2.4 cons-lambda
[2019-09-08 Sun 18:08]
Exercise 2.5 cons-pow
[2019-09-08 Sun 19:07]
Exercise 2.6 Church Numerals
[2019-09-08 Sun 19:41]
Exercise 2.7 make-interval
[2019-09-08 Sun 20:09]
Exercise 2.8 sub-interval
[2019-09-08 Sun 23:07]
Exercise 2.9 interval-width
[2019-09-08 Sun 23:15]
Exercise 2.10 div-interval-better
[2019-09-08 Sun 23:30]
Exercise 2.11 mul-interval-nine-cases
[2019-09-09 Mon 00:45]
Exercise 2.12 make-center-percent
[2019-09-09 Mon 10:11]
Exercise 2.13 formula for tolerance
[2019-09-09 Mon 10:16]
Exercise 2.14 parallel-resistors
[2019-09-09 Mon 11:24]
Exercise 2.15 better-intervals
[2019-09-09 Mon 11:34]
Exercise 2.16 interval-arithmetic
[2019-09-09 Mon 11:37]
Exercise 2.17 last-pair
[2019-09-10 Tue 10:48]
Exercise 2.18 reverse
[2019-09-10 Tue 10:57]
Exercise 2.19 coin-values
[2019-09-10 Tue 11:27]
Exercise 2.20 dotted-tail notation
[2019-09-10 Tue 18:55]
Exercise 2.21 map-square-list
[2019-09-10 Tue 19:14]
Exercise 2.22 wrong list order
[2019-09-10 Tue 19:24]
Exercise 2.23 for-each
[2019-09-10 Tue 19:33]
Exercise 2.24 list-plot-result
[2019-09-10 Tue 22:13]
Exercise 2.25 caddr
[2019-09-10 Tue 23:07]
Exercise 2.26 append cons list
[2019-09-10 Tue 23:23]
Exercise 2.27 deep-reverse
[2019-09-11 Wed 09:47]
Exercise 2.28 fringe
[2019-09-11 Wed 10:24]
Exercise 2.29 mobile
[2019-09-11 Wed 11:47]
Exercise 2.30 square-tree
[2019-09-11 Wed 14:11]
Exercise 2.31 tree-map square tree
[2019-09-11 Wed 14:38]
Exercise 2.32 subsets
[2019-09-11 Wed 14:53]
Exercise 2.33 map-append-length
[2019-09-11 Wed 23:53]
Exercise 2.34 horners-rule
[2019-09-12 Thu 00:01]
Exercise 2.35 count-leaves-accumulate
[2019-09-12 Thu 00:17]
Exercise 2.36 accumulate-n
[2019-09-12 Thu 00:26]
Exercise 2.37 matrix-*-vector
[2019-09-12 Thu 00:50]
Exercise 2.38 fold-left
[2019-09-12 Thu 09:45]
Exercise 2.39 reverse fold-right fold-left
[2019-09-12 Thu 09:52]
Exercise 2.40 unique-pairs
[2019-09-12 Thu 10:34]
Exercise 2.41 triple-sum
[2019-09-14 Sat 15:15]
Figure 2.8 A solution to the eight-queens puzzle.
[2019-09-14 Sat 15:17]
Exercise 2.42 k-queens
[2019-09-17 Tue 22:27]
Exercise 2.43 slow k-queens
[2019-09-17 Tue 22:55]
Exercise 2.44 up-split
[2019-09-23 Mon 22:54]
Exercise 2.45 split
[2019-09-24 Tue 01:37]
Exercise 2.46 make-vect
[2019-09-20 Fri 12:48]
Exercise 2.47 make-frame
[2019-09-20 Fri 14:48]
Exercise 2.48 make-segment
[2019-09-20 Fri 16:06]
Exercise 2.49 segments->painter applications
[2019-09-20 Fri 23:10]
Exercise 2.50 flip-horiz and rotate270 and rotate180
[2019-09-20 Fri 23:37]
Exercise 2.51 below
[2019-09-22 Sun 18:50]
Exercise 2.52 modify square-limit
[2019-09-24 Tue 12:25]
Exercise 2.53 quote introduction
[2019-09-24 Tue 12:36]
Exercise 2.54 equal? implementation
[2019-09-24 Tue 13:48]
Exercise 2.55 quote quote
[2019-09-24 Tue 13:48]
Exercise 2.56 differentiation-exponentiation
[2019-09-24 Tue 23:14]
Exercise 2.57 differentiate-three-sum
[2019-09-25 Wed 12:40]
Exercise 2.58 infix-notation
[2019-09-25 Wed 15:21]
Exercise 2.59 union-set
[2019-09-25 Wed 22:00]
Exercise 2.60 duplicate-set
[2019-09-25 Wed 22:17]
Exercise 2.61 sets as ordered lists
[2019-09-26 Thu 21:44]
Exercise 2.62 ordered-union-set (ordered list)
[2019-09-26 Thu 21:38]
Exercise 2.63 tree->list (binary search tree)
[2019-09-26 Thu 23:37]
Exercise 2.64 balanced-tree
[2019-09-29 Sun 17:22]
Exercise 2.65 tree-union-set
[2019-10-09 Wed 12:13]
Exercise 2.66 tree-lookup
[2019-10-09 Wed 13:03]
Exercise 2.67 Huffman decode a simple message
[2019-10-09 Wed 20:20]
Exercise 2.68 Huffman encode a simple message
[2019-10-09 Wed 20:53]
Exercise 2.69 Generate Huffman tree
[2019-10-10 Thu 11:28]
Exercise 2.70 Generate a tree and encode a song
[2019-10-10 Thu 13:11]
Exercise 2.71 Huffman tree for frequencies 5 and 10
[2019-10-10 Thu 19:22]
Exercise 2.72 Huffman order of growth
[2019-10-10 Thu 20:34]
Exercise 2.73 data-driven-deriv
[2019-10-11 Fri 11:05]
Exercise 2.74 Insatiable Enterprises
[2019-10-11 Fri 20:56]
Exercise 2.75 make-from-mag-ang message passing
[2019-10-11 Fri 21:24]
Exercise 2.76 types or functions?
[2019-10-11 Fri 21:29]
Exercise 2.77 generic-algebra-magnitude
[2019-10-12 Sat 16:01]
Exercise 2.78 Ordinary numbers for scheme
[2019-10-12 Sat 21:06]
Exercise 2.79 generic-equality
[2019-10-14 Mon 15:58]
Exercise 2.80 Generic arithmetic zero?
[2019-10-14 Mon 17:18]
Exercise 2.81 coercion to-itself
[2019-10-15 Tue 11:16]
Exercise 2.82 three-argument-coercion
[2019-10-15 Tue 21:40]
Exercise 2.83 Numeric Tower and (raise)
[2019-10-16 Wed 14:53]
Exercise 2.84 Using ~raise~ (~raise-type~) in ~apply-generic~
[2019-10-17 Thu 11:39]
Exercise 2.85 Dropping a type
[2019-10-20 Sun 13:47]
Exercise 2.86 Compound complex numbers
[2019-10-20 Sun 20:22]
Exercise 2.87 Generalized zero?
[2019-10-21 Mon 18:25]
Exercise 2.88 Subtraction of polynomials
[2019-10-22 Tue 09:55]
Exercise 2.89 Dense term-lists
[2019-10-22 Tue 11:55]
Exercise 2.90 Implementing dense polynomials as a separate package
[2019-10-22 Tue 21:31]
Exercise 2.91 Division of polynomials
[2019-10-23 Wed 00:11]
Exercise 2.92 Ordering of variables so that addition and multiplication work for different variables
[2019-10-27 Sun 13:32]
Exercise 2.93 Rational polynomials
[2019-10-27 Sun 22:36]
Exercise 2.94 Greatest-common-divisor for polynomials
[2019-10-28 Mon 00:47]
Exercise 2.95 Illustrate the non-integer problem
[2019-10-28 Mon 11:35]
Exercise 2.96 Integerizing factor
[2019-10-28 Mon 19:23]
Exercise 2.97 Reduction of polynomials
[2019-10-29 Tue 00:12]
Exercise 3.1 accumulators
[2019-10-29 Tue 10:24]
Exercise 3.2 make-monitored
[2019-10-29 Tue 11:03]
Exercise 3.3 password protection
[2019-10-29 Tue 11:17]
Exercise 3.4 call-the-cops
[2019-10-29 Tue 11:32]
Exercise 3.5 Monte-Carlo
[2019-10-30 Wed 00:12]
Exercise 3.6 reset a prng
[2019-10-30 Wed 11:42]
Exercise 3.7 Joint accounts
[2019-10-30 Wed 13:07]
Exercise 3.8 Right-to-left vs Left-to-right
[2019-10-30 Wed 13:45]
Exercise 3.9 Environment structures
[2019-11-20 Wed 14:28]
Exercise 3.10 Using ~let~ to create state variables
[2019-11-25 Mon 12:52]
Exercise 3.11 Internal definitions
[2019-11-26 Tue 12:44]
Exercise 3.12 Drawing ~append!~
[2019-11-29 Fri 11:55]
Exercise 3.13 ~make-cycle~
[2019-11-29 Fri 12:09]
Exercise 3.14 ~mystery~
[2019-11-29 Fri 21:23]
Exercise 3.15 ~set-to-wow!~
[2019-12-01 Sun 19:59]
Exercise 3.16 ~count-pairs~
[2019-12-02 Mon 00:05]
Exercise 3.17 Real ~count-pairs~
[2019-12-02 Mon 00:47]
Exercise 3.18 Finding cycles
[2019-12-02 Mon 01:04]
Exercise 3.19 Efficient finding cycles
[2019-12-02 Mon 23:29]
Exercise 3.20 Procedural ~set-car!~
[2019-12-03 Tue 14:40]
Exercise 3.21 queues
[2019-12-03 Tue 15:10]
Exercise 3.22 procedural queue
[2019-12-03 Tue 22:13]
Exercise 3.23 dequeue
[2019-12-03 Tue 23:24]
Exercise 3.24 tolerant tables
[2019-12-04 Wed 18:07]
Exercise 3.25 multilevel tables
[2019-12-06 Fri 20:35]
Exercise 3.26 binary tree table
[2019-12-06 Fri 20:53]
Exercise 3.27 memoization
[2019-12-07 Sat 16:08]
Exercise 3.28 primitive or-gate
[2019-12-08 Sun 23:43]
Exercise 3.29 Compound or-gate
[2019-12-08 Sun 23:45]
Exercise 3.30 ripple-carry adder
[2019-12-08 Sun 23:58]
Exercise 3.31 Initial propagation
[2019-12-09 Mon 00:16]
Exercise 3.32 Order matters
[2019-12-09 Mon 00:26]
Exercise 3.33 averager constraint
[2019-12-18 Wed 11:29]
Exercise 3.34 Wrong squarer
[2019-12-18 Wed 12:30]
Exercise 3.35 Correct squarer
[2019-12-18 Wed 12:47]
Exercise 3.36 Connector environment diagram
[2019-12-21 Sat 20:27]
Exercise 3.37 Expression-based constraints
[2019-12-21 Sat 21:20]
Exercise 3.38 Timing
[2019-12-21 Sat 22:48]
Exercise 3.39 Serializer
[2019-12-23 Mon 05:11]
Exercise 3.40 Three parallel multiplications
[2019-12-29 Sun 04:32]
Exercise 3.41 Better protected account
[2020-01-02 Thu 10:02]
Exercise 3.42 Saving on serializers
[2020-01-02 Thu 10:35]
Exercise 3.43 Multiple serializations
[2020-01-02 Thu 11:33]
Exercise 3.44 Transfer money
[2020-01-02 Thu 11:40]
Exercise 3.45 new plus old serializers
[2020-01-02 Thu 11:46]
Exercise 3.46 broken test-and-set!
[2020-01-02 Thu 11:56]
Exercise 3.47 semaphores
[2020-01-03 Fri 12:59]
Exercise 3.48 serialized-exchange deadlock
[2020-01-03 Fri 13:30]
Exercise 3.49 When numbering accounts doesn't work
[2020-01-03 Fri 13:41]
Exercise 3.50 stream-map multiple arguments
[2020-01-03 Fri 21:18]
Exercise 3.51 stream-show
[2020-01-03 Fri 21:28]
Exercise 3.52 streams with mind-boggling
[2020-01-03 Fri 22:17]
Exercise 3.53 stream power of two
[2020-01-03 Fri 22:40]
Exercise 3.54 mul-streams
[2020-01-03 Fri 22:47]
Exercise 3.55 streams partial-sums
[2020-01-03 Fri 23:05]
Exercise 3.56 Hamming's streams-merge
[2020-01-03 Fri 23:26]
Exercise 3.57 exponential additions fibs
[2020-01-03 Fri 23:36]
Exercise 3.58 Cryptic stream
[2020-01-03 Fri 23:50]
Exercise 3.59 power series
[2020-01-04 Sat 09:58]
integrate series
[2020-01-04 Sat 09:49]
exponential series
[2020-01-04 Sat 09:58]
Exercise 3.60 mul-series
[2020-01-04 Sat 11:07]
Exercise 3.61 power-series-inversion
[2020-01-04 Sat 13:13]
Exercise 3.62 div-series
[2020-01-04 Sat 13:21]
Exercise 3.63 sqrt-stream
[2020-01-04 Sat 20:32]
Exercise 3.64 stream-limit
[2020-01-06 Mon 09:38]
Exercise 3.65 approximating logarithm
[2020-01-06 Mon 10:34]
Exercise 3.66 lazy pairs
[2020-01-06 Mon 22:55]
Exercise 3.67 all possible pairs
[2020-01-06 Mon 23:09]
Exercise 3.68 pairs-louis
[2020-01-06 Mon 23:26]
Exercise 3.69 triples
[2020-02-17 Mon 20:10]
Exercise 3.70 merge-weighted
[2020-01-07 Tue 11:58]
Exercise 3.71 Ramanujan numbers
[2020-01-07 Tue 12:49]
Exercise 3.72 Ramanujan 3-numbers
[2020-01-08 Wed 10:27]
Figure 3.32
[2020-01-08 Wed 10:59]
Exercise 3.73 RC-circuit
[2020-01-08 Wed 13:09]
Exercise 3.74 zero-crossings
[2020-01-08 Wed 16:50]
Exercise 3.75 filtering signals
[2020-01-08 Wed 18:11]
Exercise 3.76 stream-smooth
[2020-01-08 Wed 19:56]
Exercise 3.77
[2020-01-08 Wed 20:51]
Exercise 3.78 second order differential equation
[2020-01-08 Wed 21:47]
Exercise 3.79 general second-order ode
[2020-01-08 Wed 21:57]
Figure 3.36
[2020-01-08 Wed 23:21]
Exercise 3.80 RLC circuit
[2020-01-08 Wed 23:40]
Exercise 3.81  renerator-in-streams
[2020-01-09 Thu 00:37]
Exercise 3.82 streams Monte-Carlo
[2020-01-09 Thu 09:42]
Exercise 4.1 list-of-values ordered
[2020-01-09 Thu 20:11]
Exercise 4.2 application before assignments
[2020-01-09 Thu 20:41]
Exercise 4.3 data-directed eval
[2020-01-09 Thu 21:24]
Exercise 4.4 eval-and and eval-or
[2020-01-09 Thu 22:14]
Exercise 4.5 cond with arrow
[2020-01-22 Wed 16:36]
Exercise 4.6 Implementing let
[2020-01-22 Wed 17:03]
Exercise 4.7 Implementing let*
[2020-01-22 Wed 18:09]
Exercise 4.8 Implementing named let
[2020-01-22 Wed 19:50]
Exercise 4.9 Implementing until
[2020-01-23 Thu 18:06]
Exercise 4.10 Modifying syntax
[2020-02-06 Thu 22:08]
Exercise 4.11 Environment as a list of bindings
[2020-02-11 Tue 06:58]
Exercise 4.12 Better abstractions for setting a value
[2020-02-11 Tue 19:40]
Exercise 4.13 Implementing ~make-unbound!~
[2020-02-12 Wed 08:52]
Exercise 4.14 meta map versus built-in map
[2020-02-12 Wed 08:58]
Exercise 4.15 The ~halts?~ predicate
[2020-02-12 Wed 09:24]
Exercise 4.16 Simultaneous internal definitions
[2020-02-12 Wed 13:17]
Exercise 4.17 Environment with simultaneous definitions
[2020-02-12 Wed 14:09]
Exercise 4.18 Alternative scanning
[2020-02-12 Wed 14:35]
Exercise 4.19 Mutual simultaneous definitions
[2020-02-12 Wed 19:52]
Exercise 4.20 letrec
[2020-02-13 Thu 00:49]
Exercise 4.21 Y-combinator
[2020-02-13 Thu 01:07]
Exercise 4.22 Extending evaluator to support ~let~
[2020-02-14 Fri 19:33]
Exercise 4.23 Analysing sequences
[2020-02-14 Fri 19:40]
Exercise 4.24 Analysis time test
[2020-02-14 Fri 20:12]
Exercise 4.25 lazy factorial
[2020-02-14 Fri 21:01]
Exercise 4.26 unless as a special form
[2020-02-15 Sat 04:32]
Exercise 4.27 Working with mutation in lazy interpreters
[2020-02-15 Sat 16:54]
Exercise 4.28 Eval before applying
[2020-02-15 Sat 17:01]
Exercise 4.29 Lazy evaluation is slow without memoization
[2020-02-15 Sat 17:51]
Exercise 4.30 Lazy sequences
[2020-02-15 Sat 21:32]
Exercise 4.31 Lazy arguments with syntax extension
[2020-02-15 Sat 23:44]
Exercise 4.32 streams versus lazy lists
[2020-02-16 Sun 11:49]
Exercise 4.33 quoted lazy lists
[2020-02-16 Sun 14:09]
Exercise 4.34 printing lazy lists
[2020-02-16 Sun 19:25]
Exercise 4.35 ~an-integer-between~ and Pythagorean triples
[2020-02-17 Mon 17:25]
Exercise 4.36 infinite search for Pythagorean triples
[2020-02-17 Mon 20:26]
Exercise 4.37 another method for triples
[2020-02-17 Mon 21:17]
Exercise 4.38 Logical puzzle - Not same floor
[2020-02-17 Mon 21:56]
Exercise 4.39 Order of restrictions
[2020-02-17 Mon 22:01]
Exercise 4.40 People to floor assignment
[2020-02-17 Mon 22:29]
Exercise 4.41 Ordinary scheme to solve the problem
[2020-02-18 Tue 00:12]
Exercise 4.42 The liars puzzle
[2020-02-18 Tue 12:16]
Exercise 4.43 Problematical Recreations
[2020-02-18 Tue 13:31]
Exercise 4.44 Nondeterministic eight queens
[2020-02-18 Tue 15:17]
Exercise 4.45 Five parses
[2020-02-18 Tue 19:45]
Exercise 4.46 Order of parsing
[2020-02-18 Tue 19:55]
Exercise 4.47 Parse verb phrase by Louis
[2020-02-18 Tue 20:13]
Exercise 4.48 Extending the grammar
[2020-02-18 Tue 21:06]
Exercise 4.49 Alyssa's generator
[2020-02-18 Tue 21:51]
Exercise 4.50 The ~ramb~ operator
[2020-02-17 Mon 14:56]
Exercise 4.51 Implementing ~permanent-set!~
[2020-02-18 Tue 22:34]
Exercise 4.52 ~if-fail~
[2020-02-19 Wed 00:05]
Exercise 4.53 test evaluation
[2020-02-19 Wed 00:12]
Exercise 4.54 ~analyze-require~
[2020-02-19 Wed 11:26]
Exercise 4.55 Simple queries
[2020-02-19 Wed 17:38]
Exercise 4.56 Compound queries
[2020-02-19 Wed 18:04]
Exercise 4.57 custom rules
[2020-02-19 Wed 21:36]
Exercise 4.58 big shot
[2020-02-19 Wed 22:12]
Exercise 4.59 meetings
[2020-02-19 Wed 22:57]
Exercise 4.60 pairs live near
[2020-02-19 Wed 23:20]
Exercise 4.61 next-to relation
[2020-02-19 Wed 23:31]
Exercise 4.62 last-pair
[2020-02-20 Thu 00:19]
Exercise 4.63 Genesis
[2020-02-20 Thu 10:28]
Figure 4.6 How the system works
[2020-02-20 Thu 10:59]
Exercise 4.64 broken outranked-by
[2020-02-20 Thu 12:33]
Exercise 4.65 second-degree subordinates
[2020-02-20 Thu 12:50]
Exercise 4.66 Ben's accumulation
[2020-02-20 Thu 13:08]
Exercise 4.67 loop detector
[2020-02-20 Thu 23:20]
Exercise 4.68 reverse rule
[2020-02-21 Fri 15:48]
Exercise 4.69 great grandchildren
[2020-02-21 Fri 17:43]
Exercise 4.70 Cons-stream delays its second argument
[2020-02-20 Thu 17:08]
Exercise 4.71 Louis' simple queries
[2020-02-21 Fri 20:56]
Exercise 4.72 interleave-stream
[2020-02-20 Thu 17:11]
Exercise 4.73 flatten-stream delays
[2020-02-20 Thu 17:19]
Exercise 4.74 Alyssa's streams
[2020-02-21 Fri 22:00]
Exercise 4.75 ~unique~ special form
[2020-02-21 Fri 23:19]
Exercise 4.76 improving ~and~
[2020-02-22 Sat 18:27]
Exercise 4.77 lazy queries
[2020-03-14 Sat 15:42]
Exercise 4.78 non-deterministic queries
[2020-03-15 Sun 12:40]
Exercise 4.79 prolog environments
[2020-05-10 Sun 17:59]
Figure 5.1 Data paths for a Register Machine
[2020-02-23 Sun 13:18]
Figure 5.2 Controller for a GCD Machine
[2020-02-22 Sat 22:27]
Exercise 5.1 Register machine plot
[2020-02-22 Sat 22:56]
Exercise 5.2 Register machine language description of Exercise 5.1
[2020-02-23 Sun 13:26]
Exercise 5.3 Machine for ~sqrt~ using Newton Method
[2020-02-23 Sun 20:47]
Exercise 5.4 Recursive register machines
[2020-02-24 Mon 20:49]
Exercise 5.5 Hand simulation for factorial and Fibonacci
[2020-02-24 Mon 23:27]
Exercise 5.6 Fibonacci machine extra instructions
[2020-02-24 Mon 23:43]
Exercise 5.7 Test the 5.4 machine on a simulator
[2020-02-25 Tue 10:42]
Exercise 5.8 Ambiguous labels
[2020-02-25 Tue 21:58]
Exercise 5.9 Prohibit (op)s on labels
[2020-02-25 Tue 22:23]
Exercise 5.10 Changing syntax
[2020-02-25 Tue 22:39]
Exercise 5.11 Save and restore
[2020-02-26 Wed 13:30]
Exercise 5.12 Data paths from controller
[2020-02-26 Wed 23:40]
Exercise 5.13 Registers from controller
[2020-02-27 Thu 10:57]
Exercise 5.14 Profiling
[2020-02-28 Fri 20:21]
Exercise 5.15 Instruction counting
[2020-02-28 Fri 21:36]
Exercise 5.16 Tracing execution
[2020-02-28 Fri 22:59]
Exercise 5.17 Printing labels
[2020-02-29 Sat 17:43]
Exercise 5.18 Register tracing
[2020-02-29 Sat 14:07]
Exercise 5.19 Breakpoints
[2020-02-29 Sat 17:42]
Exercise 5.20 Drawing a list ~(#1=(1 . 2) #1)~
[2020-02-29 Sat 22:15]
Exercise 5.21 Register machines for list operations
[2020-03-01 Sun 13:03]
Exercise 5.22 ~append~ and ~append!~ as register machines
[2020-03-01 Sun 14:11]
Exercise 5.23 Extending EC-evaluator with ~let~ and ~cond~
[2020-03-02 Mon 10:52]
Exercise 5.24 Making ~cond~ a primitive
[2020-03-02 Mon 14:42]
Exercise 5.25 Normal-order (lazy) evaluation
[2020-03-03 Tue 14:57]
Exercise 5.26 Explore tail recursion with ~factorial~
[2020-03-03 Tue 19:38]
Exercise 5.27 Stack depth for a recursive factorial
[2020-03-03 Tue 19:49]
Exercise 5.28 Interpreters without tail recursion
[2020-03-03 Tue 20:29]
Exercise 5.29 Stack in tree-recursive Fibonacci
[2020-03-03 Tue 20:50]
Exercise 5.30 Errors
[2020-03-04 Wed 11:35]
Exercise 5.31 a ~preserving~ mechanism
[2020-03-04 Wed 21:36]
Exercise 5.32 symbol-lookup optimization
[2020-03-04 Wed 22:51]
Exercise 5.33 compiling ~factorial-alt~
[2020-03-05 Thu 16:55]
Exercise 5.34 compiling iterative factorial
[2020-03-05 Thu 20:58]
Exercise 5.35 Decompilation
[2020-03-05 Thu 21:30]
Exercise 5.36 Order of evaluation
[2020-03-06 Fri 17:47]
Exercise 5.37 ~preserving~
[2020-03-06 Fri 21:01]
Exercise 5.38 open code primitives
[2020-03-07 Sat 18:57]
Exercise 5.39 ~lexical-address-lookup~
[2020-03-07 Sat 20:41]
Exercise 5.40 maintaining a compile-time environment
[2020-03-08 Sun 15:02]
Exercise 5.41 ~find-variable~
[2020-03-07 Sat 19:37]
Exercise 5.42 Rewrite ~compile-variable~ and ~compile-assignment~
[2020-03-08 Sun 12:59]
Exercise 5.43 Scanning out defines
[2020-03-08 Sun 21:00]
Exercise 5.44 open code with compile-time environment
[2020-03-08 Sun 21:29]
Exercise 5.45 stack usage analysis for a ~factorial~
[2020-03-09 Mon 10:09]
Exercise 5.46 stack usage analysis for ~fibonacci~
[2020-03-09 Mon 10:34]
Exercise 5.47 calling interpreted procedures
[2020-03-09 Mon 11:45]
Exercise 5.48 ~compile-and-run~
[2020-03-10 Tue 12:14]
Exercise 5.49 ~read-compile-execute-print~ loop
[2020-03-10 Tue 12:36]
Exercise 5.50 Compiling the metacircular evaluator
[2020-03-14 Sat 15:52]
Exercise 5.51 Translating the EC-evaluator into a low-level language
[2020-04-13 Mon 11:45]
Exercise 5.52 Making a compiler for scheme
[2020-05-06 Wed 11:09]
#+end_example

** Appendix 2

Full data on the study sessions.

#+begin_example
    CLOCK: [2020-05-10 Sun 14:39]--[2020-05-10 Sun 18:00] =>  3:21
    CLOCK: [2020-05-09 Sat 19:13]--[2020-05-09 Sat 22:13] =>  3:00
    CLOCK: [2020-05-09 Sat 09:34]--[2020-05-09 Sat 14:34] =>  5:00
    CLOCK: [2020-05-08 Fri 21:45]--[2020-05-08 Fri 23:17] =>  1:32
    CLOCK: [2020-05-08 Fri 18:30]--[2020-05-08 Fri 21:18] =>  2:48
    CLOCK: [2020-05-06 Wed 10:12]--[2020-05-06 Wed 11:09] =>  0:57
    CLOCK: [2020-05-05 Tue 12:11]--[2020-05-06 Wed 00:00] => 11:49
    CLOCK: [2020-05-04 Mon 18:20]--[2020-05-05 Tue 00:30] =>  6:10
    CLOCK: [2020-05-04 Mon 14:02]--[2020-05-04 Mon 17:43] =>  3:41
    CLOCK: [2020-05-03 Sun 21:03]--[2020-05-03 Sun 22:02] =>  0:59
    CLOCK: [2020-04-30 Thu 09:28]--[2020-04-30 Thu 11:23] =>  1:55
    CLOCK: [2020-04-29 Wed 20:00]--[2020-04-29 Wed 23:25] =>  3:25
    CLOCK: [2020-04-28 Tue 22:55]--[2020-04-29 Wed 00:11] =>  1:16
    CLOCK: [2020-04-28 Tue 21:00]--[2020-04-28 Tue 22:50] =>  1:50
    CLOCK: [2020-04-27 Mon 20:09]--[2020-04-27 Mon 22:09] =>  2:00
    CLOCK: [2020-04-26 Sun 20:10]--[2020-04-26 Sun 23:52] =>  3:42
    CLOCK: [2020-04-21 Tue 11:01]--[2020-04-21 Tue 12:26] =>  1:25
    CLOCK: [2020-04-11 Sat 11:50]--[2020-04-11 Sat 15:50] =>  4:00
    CLOCK: [2020-04-10 Fri 09:50]--[2020-04-10 Fri 14:26] =>  4:36
    CLOCK: [2020-04-09 Thu 19:50]--[2020-04-09 Thu 23:10] =>  3:20
    CLOCK: [2020-04-09 Thu 09:55]--[2020-04-09 Thu 13:00] =>  3:05
    CLOCK: [2020-04-08 Wed 22:50]--[2020-04-08 Wed 23:55] =>  1:05
    CLOCK: [2020-04-08 Wed 18:30]--[2020-04-08 Wed 21:11] =>  2:41 
    CLOCK: [2020-04-08 Wed 09:15]--[2020-04-08 Wed 12:15] =>  3:00
    CLOCK: [2020-04-07 Tue 20:46]--[2020-04-07 Tue 23:37] =>  2:51
    CLOCK: [2020-04-07 Tue 09:41]--[2020-04-07 Tue 11:57] =>  2:16
    CLOCK: [2020-04-06 Mon 18:58]--[2020-04-06 Mon 21:20] =>  2:22
    CLOCK: [2020-04-06 Mon 12:09]--[2020-04-06 Mon 14:15] =>  2:06
    CLOCK: [2020-04-05 Sun 11:30]--[2020-04-05 Sun 15:11] =>  3:41
    CLOCK: [2020-04-04 Sat 22:08]--[2020-04-04 Sat 22:45] =>  0:37
    CLOCK: [2020-04-04 Sat 17:54]--[2020-04-04 Sat 20:50] =>  2:56
    CLOCK: [2020-04-04 Sat 17:24]--[2020-04-04 Sat 17:41] =>  0:17
    CLOCK: [2020-04-04 Sat 15:15]--[2020-04-04 Sat 16:10] =>  0:55
    CLOCK: [2020-04-03 Fri 20:22]--[2020-04-03 Fri 22:21] =>  1:59
    CLOCK: [2020-04-01 Wed 13:05]--[2020-04-01 Wed 15:05] =>  2:00
    CLOCK: [2020-03-29 Sun 13:05]--[2020-03-29 Sun 22:05] =>  9:00
    CLOCK: [2020-03-28 Sat 13:04]--[2020-03-28 Sat 22:04] =>  9:00
    CLOCK: [2020-03-26 Thu 20:20]--[2020-03-26 Thu 23:33] =>  3:13
    CLOCK: [2020-03-26 Thu 10:43]--[2020-03-26 Thu 14:39] =>  3:56
    CLOCK: [2020-03-24 Tue 20:00]--[2020-03-24 Tue 23:50] =>  3:50
    CLOCK: [2020-03-24 Tue 09:10]--[2020-03-24 Tue 12:34] =>  3:24
    CLOCK: [2020-03-23 Mon 19:56]--[2020-03-23 Mon 23:06] =>  3:10
    CLOCK: [2020-03-23 Mon 10:23]--[2020-03-23 Mon 13:23] =>  3:00
    CLOCK: [2020-03-23 Mon 09:06]--[2020-03-23 Mon 10:56] =>  1:50
    CLOCK: [2020-03-22 Sun 12:45]--[2020-03-22 Sun 22:45] => 10:00
    CLOCK: [2020-03-21 Sat 19:07]--[2020-03-21 Sat 21:35] =>  2:28
    CLOCK: [2020-03-17 Tue 19:11]--[2020-03-17 Tue 22:11] =>  3:00
    CLOCK: [2020-03-15 Sun 09:10]--[2020-03-15 Sun 12:20] =>  3:10
    CLOCK: [2020-03-14 Sat 23:01]--[2020-03-14 Sat 23:54] =>  0:53
    CLOCK: [2020-03-14 Sat 20:46]--[2020-03-14 Sat 23:01] =>  2:15
    CLOCK: [2020-03-14 Sat 20:39]--[2020-03-14 Sat 20:46] =>  0:07
    CLOCK: [2020-03-14 Sat 17:23]--[2020-03-14 Sat 20:39] =>  3:16
    CLOCK: [2020-03-14 Sat 12:00]--[2020-03-14 Sat 15:23] =>  3:23
    CLOCK: [2020-03-13 Fri 20:01]--[2020-03-13 Fri 23:01] =>  3:00
    CLOCK: [2020-03-13 Fri 09:20]--[2020-03-13 Fri 11:58] =>  2:38
    CLOCK: [2020-03-12 Thu 20:30]--[2020-03-12 Thu 23:29] =>  2:59
    CLOCK: [2020-03-11 Wed 12:12]--[2020-03-11 Wed 13:18] =>  1:06
    CLOCK: [2020-03-11 Wed 10:45]--[2020-03-11 Wed 11:09] =>  0:24
    CLOCK: [2020-03-11 Wed 09:15]--[2020-03-11 Wed 10:45] =>  1:30
    CLOCK: [2020-03-10 Tue 20:22]--[2020-03-11 Wed 00:09] =>  3:47
    CLOCK: [2020-03-10 Tue 09:08]--[2020-03-10 Tue 13:44] =>  4:36
    CLOCK: [2020-03-09 Mon 22:28]--[2020-03-09 Mon 23:32] =>  1:04
    CLOCK: [2020-03-09 Mon 09:08]--[2020-03-09 Mon 11:59] =>  2:51
    CLOCK: [2020-03-08 Sun 18:30]--[2020-03-08 Sun 21:29] =>  2:59
    CLOCK: [2020-03-08 Sun 16:51]--[2020-03-08 Sun 18:08] =>  1:17
    CLOCK: [2020-03-08 Sun 13:50]--[2020-03-08 Sun 15:36] =>  1:46
    CLOCK: [2020-03-08 Sun 11:56]--[2020-03-08 Sun 13:28] =>  1:32
    CLOCK: [2020-03-07 Sat 18:00]--[2020-03-07 Sat 21:36] =>  3:36
    CLOCK: [2020-03-07 Sat 11:35]--[2020-03-07 Sat 16:09] =>  4:34
    CLOCK: [2020-03-06 Fri 20:19]--[2020-03-06 Fri 21:48] =>  1:29
    CLOCK: [2020-03-06 Fri 13:11]--[2020-03-06 Fri 14:16] =>  1:05
    CLOCK: [2020-03-06 Fri 09:42]--[2020-03-06 Fri 12:39] =>  2:57
    CLOCK: [2020-03-05 Thu 19:34]--[2020-03-05 Thu 21:34] =>  2:00
    CLOCK: [2020-03-05 Thu 08:58]--[2020-03-05 Thu 13:24] =>  4:26
    CLOCK: [2020-03-04 Wed 19:51]--[2020-03-04 Wed 22:51] =>  3:00
    CLOCK: [2020-03-04 Wed 11:36]--[2020-03-04 Wed 12:31] =>  0:55
    CLOCK: [2020-03-04 Wed 09:32]--[2020-03-04 Wed 11:01] =>  1:29
    CLOCK: [2020-03-03 Tue 19:13]--[2020-03-03 Tue 21:46] =>  2:33
    CLOCK: [2020-03-03 Tue 12:20]--[2020-03-03 Tue 14:58] =>  2:38
    CLOCK: [2020-03-03 Tue 09:13]--[2020-03-03 Tue 11:57] =>  2:44
    CLOCK: [2020-03-02 Mon 18:30]--[2020-03-02 Mon 18:50] =>  0:20
    CLOCK: [2020-03-02 Mon 12:01]--[2020-03-02 Mon 14:43] =>  2:42
    CLOCK: [2020-03-02 Mon 09:02]--[2020-03-02 Mon 11:30] =>  2:28
    CLOCK: [2020-03-01 Sun 19:07]--[2020-03-01 Sun 21:25] =>  2:18
    CLOCK: [2020-03-01 Sun 17:50]--[2020-03-01 Sun 18:41] =>  0:51
    CLOCK: [2020-03-01 Sun 11:09]--[2020-03-01 Sun 15:15] =>  4:06
    CLOCK: [2020-02-29 Sat 21:30]--[2020-02-29 Sat 22:16] =>  0:46
    CLOCK: [2020-02-29 Sat 12:48]--[2020-02-29 Sat 19:17] =>  6:29
    CLOCK: [2020-02-28 Fri 20:21]--[2020-02-28 Fri 23:10] =>  2:49
    CLOCK: [2020-02-28 Fri 18:26]--[2020-02-28 Fri 19:22] =>  0:56
    CLOCK: [2020-02-27 Thu 09:20]--[2020-02-27 Thu 10:57] =>  1:37
    CLOCK: [2020-02-26 Wed 20:47]--[2020-02-26 Wed 23:44] =>  2:57
    CLOCK: [2020-02-26 Wed 12:07]--[2020-02-26 Wed 13:40] =>  1:33
    CLOCK: [2020-02-26 Wed 09:29]--[2020-02-26 Wed 11:00] =>  1:31
    CLOCK: [2020-02-25 Tue 19:18]--[2020-02-25 Tue 22:51] =>  3:33
    CLOCK: [2020-02-25 Tue 09:01]--[2020-02-25 Tue 10:42] =>  1:41
    CLOCK: [2020-02-24 Mon 19:23]--[2020-02-25 Tue 00:15] =>  4:52
    CLOCK: [2020-02-24 Mon 13:00]--[2020-02-24 Mon 13:36] =>  0:36
    CLOCK: [2020-02-24 Mon 10:08]--[2020-02-24 Mon 12:39] =>  2:31
    CLOCK: [2020-02-23 Sun 19:20]--[2020-02-23 Sun 19:26] =>  0:06
    CLOCK: [2020-02-23 Sun 12:52]--[2020-02-23 Sun 16:45] =>  3:53
    CLOCK: [2020-02-22 Sat 21:35]--[2020-02-23 Sun 00:25] =>  2:50
    CLOCK: [2020-02-22 Sat 19:59]--[2020-02-22 Sat 21:03] =>  1:04
    CLOCK: [2020-02-22 Sat 12:20]--[2020-02-22 Sat 18:35] =>  6:15
    CLOCK: [2020-02-21 Fri 21:52]--[2020-02-22 Sat 00:30] =>  2:38
    CLOCK: [2020-02-21 Fri 17:30]--[2020-02-21 Fri 18:51] =>  1:21
    CLOCK: [2020-02-21 Fri 10:40]--[2020-02-21 Fri 16:40] =>  6:00
    CLOCK: [2020-02-20 Thu 17:00]--[2020-02-20 Thu 23:33] =>  6:33
    CLOCK: [2020-02-20 Thu 14:43]--[2020-02-20 Thu 15:08] =>  0:25
    CLOCK: [2020-02-20 Thu 10:05]--[2020-02-20 Thu 13:54] =>  3:49
    CLOCK: [2020-02-19 Wed 21:50]--[2020-02-20 Thu 00:36] =>  2:46
    CLOCK: [2020-02-19 Wed 19:50]--[2020-02-19 Wed 21:30] =>  1:40
    CLOCK: [2020-02-19 Wed 13:34]--[2020-02-19 Wed 18:15] =>  4:41
    CLOCK: [2020-02-19 Wed 11:10]--[2020-02-19 Wed 13:34] =>  2:24
    CLOCK: [2020-02-18 Tue 21:27]--[2020-02-19 Wed 00:27] =>  3:00
    CLOCK: [2020-02-18 Tue 19:02]--[2020-02-18 Tue 20:13] =>  1:11
    CLOCK: [2020-02-18 Tue 16:58]--[2020-02-18 Tue 18:36] =>  1:38
    CLOCK: [2020-02-18 Tue 10:55]--[2020-02-18 Tue 15:21] =>  4:26
    CLOCK: [2020-02-17 Mon 19:20]--[2020-02-18 Tue 00:12] =>  4:52
    CLOCK: [2020-02-17 Mon 15:20]--[2020-02-17 Mon 18:00] =>  2:40
    CLOCK: [2020-02-17 Mon 14:17]--[2020-02-17 Mon 15:09] =>  0:52
    CLOCK: [2020-02-16 Sun 21:21]--[2020-02-17 Mon 00:52] =>  3:31
    CLOCK: [2020-02-16 Sun 20:03]--[2020-02-16 Sun 20:14] =>  0:11
    CLOCK: [2020-02-16 Sun 19:00]--[2020-02-16 Sun 19:30] =>  0:30
    CLOCK: [2020-02-16 Sun 16:06]--[2020-02-16 Sun 18:38] =>  2:32
    CLOCK: [2020-02-16 Sun 12:59]--[2020-02-16 Sun 14:37] =>  1:38
    CLOCK: [2020-02-16 Sun 10:30]--[2020-02-16 Sun 12:22] =>  1:52
    CLOCK: [2020-02-15 Sat 22:10]--[2020-02-15 Sat 23:52] =>  1:42
    CLOCK: [2020-02-15 Sat 21:01]--[2020-02-15 Sat 21:50] =>  0:49
    CLOCK: [2020-02-15 Sat 15:03]--[2020-02-15 Sat 18:34] =>  3:31
    CLOCK: [2020-02-14 Fri 18:53]--[2020-02-14 Fri 21:21] =>  2:28
    CLOCK: [2020-02-13 Thu 16:15]--[2020-02-13 Thu 17:21] =>  1:06
    CLOCK: [2020-02-13 Thu 00:12]--[2020-02-13 Thu 01:45] =>  1:33
    CLOCK: [2020-02-12 Wed 18:36]--[2020-02-12 Wed 22:30] =>  3:54
    CLOCK: [2020-02-12 Wed 13:40]--[2020-02-12 Wed 14:55] =>  1:15
    CLOCK: [2020-02-12 Wed 08:37]--[2020-02-12 Wed 12:20] =>  3:43
    CLOCK: [2020-02-11 Tue 18:51]--[2020-02-11 Tue 21:54] =>  3:03
    CLOCK: [2020-02-11 Tue 04:30]--[2020-02-11 Tue 08:09] =>  3:39
    CLOCK: [2020-02-10 Mon 06:42]--[2020-02-10 Mon 07:28] =>  0:46
    CLOCK: [2020-02-01 Sat 15:05]--[2020-02-01 Sat 15:36] =>  0:31
    CLOCK: [2020-01-23 Thu 17:06]--[2020-01-23 Thu 18:51] =>  1:45
    CLOCK: [2020-01-22 Wed 20:53]--[2020-01-22 Wed 21:05] =>  0:12
    CLOCK: [2020-01-22 Wed 13:40]--[2020-01-22 Wed 20:20] =>  6:40
    CLOCK: [2020-01-21 Tue 15:33]--[2020-01-21 Tue 16:57] =>  1:24
    CLOCK: [2020-01-17 Fri 19:13]--[2020-01-17 Fri 23:00] =>  3:47
    CLOCK: [2020-01-11 Sat 10:56]--[2020-01-11 Sat 18:24] =>  7:28
    CLOCK: [2020-01-10 Fri 22:20]--[2020-01-10 Fri 23:56] =>  1:36
    CLOCK: [2020-01-10 Fri 09:40]--[2020-01-10 Fri 13:20] =>  3:40
    CLOCK: [2020-01-09 Thu 20:10]--[2020-01-09 Thu 22:15] =>  2:05
    CLOCK: [2020-01-09 Thu 08:50]--[2020-01-09 Thu 09:55] =>  1:05
    CLOCK: [2020-01-08 Wed 19:21]--[2020-01-09 Thu 00:42] =>  5:21
    CLOCK: [2020-01-08 Wed 09:20]--[2020-01-08 Wed 13:48] =>  4:28
    CLOCK: [2020-01-07 Tue 16:31]--[2020-01-07 Tue 18:31] =>  2:00
    CLOCK: [2020-01-07 Tue 08:55]--[2020-01-07 Tue 12:49] =>  3:54
    CLOCK: [2020-01-06 Mon 22:30]--[2020-01-06 Mon 23:31] =>  1:01
    CLOCK: [2020-01-06 Mon 09:20]--[2020-01-06 Mon 11:56] =>  2:36
    CLOCK: [2020-01-04 Sat 20:25]--[2020-01-04 Sat 21:09] =>  0:44
    CLOCK: [2020-01-04 Sat 09:37]--[2020-01-04 Sat 13:00] =>  3:23
    CLOCK: [2020-01-03 Fri 21:13]--[2020-01-03 Fri 23:59] =>  2:46
    CLOCK: [2020-01-03 Fri 18:13]--[2020-01-03 Fri 19:13] =>  1:00
    CLOCK: [2020-01-03 Fri 12:08]--[2020-01-03 Fri 14:12] =>  2:04
    CLOCK: [2020-01-02 Thu 09:35]--[2020-01-02 Thu 11:58] =>  2:23
    CLOCK: [2019-12-29 Sun 02:12]--[2019-12-29 Sun 05:42] =>  3:30
    CLOCK: [2019-12-26 Thu 16:59]--[2019-12-26 Thu 19:51] =>  2:52
    CLOCK: [2019-12-23 Mon 05:03]--[2019-12-23 Mon 05:31] =>  0:28
    CLOCK: [2019-12-23 Mon 03:02]--[2019-12-23 Mon 04:03] =>  1:01
    CLOCK: [2019-12-22 Sun 16:51]--[2019-12-22 Sun 18:40] =>  1:49
    CLOCK: [2019-12-21 Sat 19:23]--[2019-12-22 Sun 00:19] =>  4:56
    CLOCK: [2019-12-20 Fri 14:10]--[2019-12-20 Fri 17:11] =>  3:01
    CLOCK: [2019-12-19 Thu 23:20]--[2019-12-19 Thu 23:38] =>  0:18
    CLOCK: [2019-12-18 Wed 10:47]--[2019-12-18 Wed 12:47] =>  2:00
    CLOCK: [2019-12-09 Mon 10:47]--[2019-12-09 Mon 13:21] =>  2:34
    CLOCK: [2019-12-08 Sun 17:47]--[2019-12-08 Sun 22:47] =>  5:00
    CLOCK: [2019-12-07 Sat 20:14]--[2019-12-07 Sat 23:15] =>  3:01
    CLOCK: [2019-12-06 Fri 19:04]--[2019-12-06 Fri 20:34] =>  1:30
    CLOCK: [2019-12-04 Wed 22:42]--[2019-12-05 Thu 00:42] =>  2:00
    CLOCK: [2019-12-04 Wed 12:36]--[2019-12-04 Wed 13:05] =>  0:29
    CLOCK: [2019-12-03 Tue 22:18]--[2019-12-03 Tue 23:27] =>  1:09
    CLOCK: [2019-12-03 Tue 21:21]--[2019-12-03 Tue 22:18] =>  0:57
    CLOCK: [2019-12-03 Tue 12:40]--[2019-12-03 Tue 15:25] =>  2:45
    CLOCK: [2019-12-02 Mon 20:06]--[2019-12-02 Mon 22:06] =>  2:00
    CLOCK: [2019-12-01 Sun 22:07]--[2019-12-02 Mon 00:07] =>  2:00
    CLOCK: [2019-12-01 Sun 18:59]--[2019-12-01 Sun 19:59] =>  1:00
    CLOCK: [2019-11-30 Sat 14:19]--[2019-11-30 Sat 15:15] =>  0:56
    CLOCK: [2019-11-29 Fri 20:07]--[2019-11-29 Fri 21:19] =>  1:12
    CLOCK: [2019-11-28 Thu 09:30]--[2019-11-28 Thu 15:00] =>  5:30
    CLOCK: [2019-11-26 Tue 09:15]--[2019-11-26 Tue 12:57] =>  3:42
    CLOCK: [2019-11-25 Mon 10:35]--[2019-11-25 Mon 13:02] =>  2:27
    CLOCK: [2019-11-20 Wed 12:08]--[2019-11-20 Wed 14:19] =>  2:11
    CLOCK: [2019-11-20 Wed 09:25]--[2019-11-20 Wed 11:32] =>  2:07
    CLOCK: [2019-11-19 Tue 11:45]--[2019-11-19 Tue 14:42] =>  2:57
    CLOCK: [2019-11-13 Wed 20:52]--[2019-11-13 Wed 22:25] =>  1:33
    CLOCK: [2019-11-12 Tue 19:47]--[2019-11-12 Tue 21:14] =>  1:27
    CLOCK: [2019-11-12 Tue 09:30]--[2019-11-12 Tue 11:49] =>  2:19
    CLOCK: [2019-11-11 Mon 21:03]--[2019-11-11 Mon 23:03] =>  2:00
    CLOCK: [2019-11-10 Sun 21:45]--[2019-11-10 Sun 23:25] =>  1:40
    CLOCK: [2019-10-31 Thu 09:20]--[2019-10-31 Thu 11:07] =>  1:47
    CLOCK: [2019-10-30 Wed 10:35]--[2019-10-30 Wed 13:55] =>  3:20
    CLOCK: [2019-10-29 Tue 22:35]--[2019-10-30 Wed 00:13] =>  1:38
    CLOCK: [2019-10-29 Tue 09:33]--[2019-10-29 Tue 11:33] =>  2:00
    CLOCK: [2019-10-28 Mon 21:52]--[2019-10-29 Tue 00:14] =>  2:22
    CLOCK: [2019-10-28 Mon 18:23]--[2019-10-28 Mon 19:23] =>  1:00
    CLOCK: [2019-10-28 Mon 09:07]--[2019-10-28 Mon 15:10] =>  6:03
    CLOCK: [2019-10-27 Sun 20:44]--[2019-10-28 Mon 00:48] =>  4:04
    CLOCK: [2019-10-27 Sun 14:17]--[2019-10-27 Sun 15:42] =>  1:25
    CLOCK: [2019-10-27 Sun 12:15]--[2019-10-27 Sun 13:26] =>  1:11
    CLOCK: [2019-10-26 Sat 13:53]--[2019-10-26 Sat 14:10] =>  0:17
    CLOCK: [2019-10-26 Sat 10:15]--[2019-10-26 Sat 10:58] =>  0:43
    CLOCK: [2019-10-25 Fri 15:12]--[2019-10-25 Fri 17:55] =>  2:43
    CLOCK: [2019-10-25 Fri 09:10]--[2019-10-25 Fri 09:59] =>  0:49
    CLOCK: [2019-10-24 Thu 22:23]--[2019-10-25 Fri 00:05] =>  1:42
    CLOCK: [2019-10-24 Thu 18:45]--[2019-10-24 Thu 21:21] =>  2:36
    CLOCK: [2019-10-24 Thu 09:03]--[2019-10-24 Thu 10:47] =>  1:44
    CLOCK: [2019-10-23 Wed 21:24]--[2019-10-23 Wed 23:49] =>  2:25
    CLOCK: [2019-10-23 Wed 09:09]--[2019-10-23 Wed 10:55] =>  1:46
    CLOCK: [2019-10-22 Tue 22:35]--[2019-10-23 Wed 00:08] =>  1:33
    CLOCK: [2019-10-22 Tue 19:10]--[2019-10-22 Tue 21:38] =>  2:28
    CLOCK: [2019-10-22 Tue 09:18]--[2019-10-22 Tue 12:02] =>  2:44
    CLOCK: [2019-10-21 Mon 23:39]--[2019-10-21 Mon 23:49] =>  0:10
    CLOCK: [2019-10-21 Mon 17:23]--[2019-10-21 Mon 18:28] =>  1:05
    CLOCK: [2019-10-21 Mon 09:05]--[2019-10-21 Mon 13:58] =>  4:53
    CLOCK: [2019-10-20 Sun 23:27]--[2019-10-21 Mon 00:00] =>  0:33
    CLOCK: [2019-10-20 Sun 19:32]--[2019-10-20 Sun 20:23] =>  0:51
    CLOCK: [2019-10-20 Sun 12:55]--[2019-10-20 Sun 14:45] =>  1:50
    CLOCK: [2019-10-19 Sat 19:25]--[2019-10-19 Sat 20:45] =>  1:20
    CLOCK: [2019-10-19 Sat 16:12]--[2019-10-19 Sat 18:47] =>  2:35
    CLOCK: [2019-10-17 Thu 19:18]--[2019-10-17 Thu 22:55] =>  3:37
    CLOCK: [2019-10-17 Thu 09:30]--[2019-10-17 Thu 11:42] =>  2:12
    CLOCK: [2019-10-16 Wed 09:08]--[2019-10-16 Wed 10:08] =>  1:00
    CLOCK: [2019-10-15 Tue 22:35]--[2019-10-15 Tue 23:30] =>  0:55
    CLOCK: [2019-10-15 Tue 19:30]--[2019-10-15 Tue 21:40] =>  2:10
    CLOCK: [2019-10-15 Tue 09:10]--[2019-10-15 Tue 12:56] =>  3:46
    CLOCK: [2019-10-14 Mon 19:51]--[2019-10-14 Mon 23:10] =>  3:19
    CLOCK: [2019-10-12 Sat 20:05]--[2019-10-12 Sat 21:33] =>  1:28
    CLOCK: [2019-10-12 Sat 15:56]--[2019-10-12 Sat 16:07] =>  0:11
    CLOCK: [2019-10-12 Sat 10:31]--[2019-10-12 Sat 12:31] =>  2:00
    CLOCK: [2019-10-11 Fri 19:55]--[2019-10-11 Fri 22:34] =>  2:39
    CLOCK: [2019-10-11 Fri 17:55]--[2019-10-11 Fri 19:28] =>  1:33
    CLOCK: [2019-10-11 Fri 14:35]--[2019-10-11 Fri 14:47] =>  0:12
    CLOCK: [2019-10-11 Fri 09:10]--[2019-10-11 Fri 11:10] =>  2:00
    CLOCK: [2019-10-10 Thu 20:26]--[2019-10-10 Thu 21:48] =>  1:22
    CLOCK: [2019-10-10 Thu 17:26]--[2019-10-10 Thu 19:40] =>  2:14
    CLOCK: [2019-10-10 Thu 12:15]--[2019-10-10 Thu 14:37] =>  2:22
    CLOCK: [2019-10-10 Thu 08:50]--[2019-10-10 Thu 11:29] =>  2:39
    CLOCK: [2019-10-09 Wed 20:16]--[2019-10-09 Wed 20:55] =>  0:39
    CLOCK: [2019-10-09 Wed 16:46]--[2019-10-09 Wed 17:55] =>  1:09
    CLOCK: [2019-10-09 Wed 11:27]--[2019-10-09 Wed 13:38] =>  2:11
    CLOCK: [2019-09-27 Fri 08:56]--[2019-09-27 Fri 10:20] =>  1:24
    CLOCK: [2019-09-26 Thu 21:25]--[2019-09-26 Thu 21:57] =>  0:32
    CLOCK: [2019-09-25 Wed 21:55]--[2019-09-25 Wed 22:18] =>  0:23
    CLOCK: [2019-09-25 Wed 13:20]--[2019-09-25 Wed 14:51] =>  1:31
    CLOCK: [2019-09-25 Wed 09:20]--[2019-09-25 Wed 11:25] =>  2:05
    CLOCK: [2019-09-24 Tue 22:10]--[2019-09-24 Tue 23:16] =>  1:06
    CLOCK: [2019-09-24 Tue 12:05]--[2019-09-24 Tue 13:28] =>  1:23
    CLOCK: [2019-09-24 Tue 01:17]--[2019-09-24 Tue 02:15] =>  0:58
    CLOCK: [2019-09-23 Mon 21:26]--[2019-09-23 Mon 22:57] =>  1:31
    CLOCK: [2019-09-22 Sun 14:52]--[2019-09-22 Sun 18:51] =>  3:59
    CLOCK: [2019-09-21 Sat 16:50]--[2019-09-21 Sat 17:55] =>  1:05
    CLOCK: [2019-09-21 Sat 12:31]--[2019-09-21 Sat 15:44] =>  3:13
    CLOCK: [2019-09-20 Fri 22:05]--[2019-09-21 Sat 00:05] =>  2:00
    CLOCK: [2019-09-20 Fri 14:38]--[2019-09-20 Fri 17:20] =>  2:42
    CLOCK: [2019-09-20 Fri 11:42]--[2019-09-20 Fri 12:48] =>  1:06
    CLOCK: [2019-09-19 Thu 21:14]--[2019-09-20 Fri 00:33] =>  3:19
    CLOCK: [2019-09-19 Thu 09:15]--[2019-09-19 Thu 11:14] =>  1:59
    CLOCK: [2019-09-18 Wed 20:55]--[2019-09-18 Wed 23:25] =>  2:30
    CLOCK: [2019-09-14 Sat 14:20]--[2019-09-14 Sat 16:57] =>  2:37
    CLOCK: [2019-09-12 Thu 09:31]--[2019-09-12 Thu 10:36] =>  1:05
    CLOCK: [2019-09-11 Wed 22:40]--[2019-09-12 Thu 01:41] =>  3:01
    CLOCK: [2019-09-11 Wed 12:11]--[2019-09-11 Wed 15:16] =>  3:05
    CLOCK: [2019-09-11 Wed 09:19]--[2019-09-11 Wed 11:49] =>  2:30
    CLOCK: [2019-09-10 Tue 16:30]--[2019-09-10 Tue 19:35] =>  3:05
    CLOCK: [2019-09-10 Tue 14:30]--[2019-09-10 Tue 14:41] =>  0:11
    CLOCK: [2019-09-10 Tue 10:27]--[2019-09-10 Tue 11:27] =>  1:00
    CLOCK: [2019-09-09 Mon 09:29]--[2019-09-09 Mon 12:45] =>  3:16
    CLOCK: [2019-09-08 Sun 23:07]--[2019-09-09 Mon 00:40] =>  1:33
    CLOCK: [2019-09-08 Sun 15:10]--[2019-09-08 Sun 21:07] =>  5:57
    CLOCK: [2019-09-06 Fri 12:05]--[2019-09-06 Fri 13:40] =>  1:35
    CLOCK: [2019-09-04 Wed 20:01]--[2019-09-04 Wed 23:19] =>  3:18
    CLOCK: [2019-09-04 Wed 17:21]--[2019-09-04 Wed 20:00] =>  2:39
    CLOCK: [2019-09-04 Wed 09:12]--[2019-09-04 Wed 12:07] =>  2:55
    CLOCK: [2019-09-03 Tue 19:40]--[2019-09-04 Wed 01:20] =>  5:40
    CLOCK: [2019-09-03 Tue 11:12]--[2019-09-03 Tue 14:36] =>  3:24
    CLOCK: [2019-09-03 Tue 10:00]--[2019-09-03 Tue 10:39] =>  0:39
    CLOCK: [2019-09-02 Mon 19:55]--[2019-09-03 Tue 00:00] =>  4:05
    CLOCK: [2019-09-02 Mon 09:53]--[2019-09-02 Mon 13:37] =>  3:44
    CLOCK: [2019-09-01 Sun 19:10]--[2019-09-02 Mon 00:46] =>  5:36
    CLOCK: [2019-08-25 Sun 14:15]--[2019-08-25 Sun 21:55] =>  7:40
    CLOCK: [2019-08-22 Thu 15:01]--[2019-08-22 Thu 19:39] =>  4:38
    CLOCK: [2019-08-22 Thu 09:12]--[2019-08-22 Thu 13:30] =>  4:18
    CLOCK: [2019-08-21 Wed 21:15]--[2019-08-22 Thu 00:17] =>  3:02
    CLOCK: [2019-08-21 Wed 12:21]--[2019-08-21 Wed 14:39] =>  2:18
    CLOCK: [2019-08-20 Tue 10:57]--[2019-08-20 Tue 15:04] =>  4:07
    CLOCK: [2019-08-19 Mon 09:19]--[2019-08-19 Mon 13:32] =>  4:13

#+end_example
